version: "3.9"
services:
  spark-master:
    image: "spark-master"
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-net
    hostname: "spark-master"
    deploy:
      placement:
        # set node labels using docker node update --label-add key=value <NODE ID> from swarm manager
        constraints:
          - node.labels.role==master
  spark-worker:
    image: "spark-worker"
    ports:
      - "8081:8081"
    environment:
      - CORES=1
      - MEMORY=1G
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    hostname: "spark-worker1"
    depends_on:
      - spark-master
    deploy:
      placement:
        # set node labels using docker node update --label-add key=value <NODE ID> from swarm manager
        constraints:
          - node.labels.role==worker
      replicas: 1
    networks:
      - spark-net
networks:
  spark-net:
    driver: overlay